config/routes.rb
WODx::Application.routes.draw do
  
  devise_for :users,  :controllers => { :registrations => "users/registrations" }

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :equipment

  resources :workouts
  
  root :to => "home#index"
  match 'workouts/random', :to => 'workouts#random'

  match ':controller(/:action(/:id))(.:format)'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
      if user.role? :admin
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :workouts
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_and_belongs_to_many :roles
  
  def role?(role)
      return self.roles.find_by_name(role.to_s.camelize)
  end
end

app/models/workout.rb
class Workout < ActiveRecord::Base
  attr_accessible :description, :source, :title, :equipment_ids, :equipment, :sample_size, :mean, :median, :standard_deviation
  has_and_belongs_to_many :equipment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to root_url
  end
  
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = exception.message
    redirect_to root_url
  end
end

app/controllers/equipment_controller.rb
class EquipmentController < ApplicationController
  # GET /equipment
  # GET /equipment.json
  
  load_and_authorize_resource
  
  def index
    @equipment = Equipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1
  # GET /equipment/1.json
  def show
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/new
  # GET /equipment/new.json
  def new
    @equipment = Equipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @equipment }
    end
  end

  # GET /equipment/1/edit
  def edit
    @equipment = Equipment.find(params[:id])
  end

  # POST /equipment
  # POST /equipment.json
  def create
    @equipment = Equipment.new(params[:equipment])

    respond_to do |format|
      if @equipment.save
        format.html { redirect_to @equipment, notice: 'Equipment was successfully created.' }
        format.json { render json: @equipment, status: :created, location: @equipment }
      else
        format.html { render action: "new" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /equipment/1
  # PUT /equipment/1.json
  def update
    @equipment = Equipment.find(params[:id])

    respond_to do |format|
      if @equipment.update_attributes(params[:equipment])
        format.html { redirect_to @equipment, notice: 'Equipment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @equipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipment/1
  # DELETE /equipment/1.json
  def destroy
    @equipment = Equipment.find(params[:id])
    @equipment.destroy

    respond_to do |format|
      format.html { redirect_to equipment_index_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :check_permissions, :only => [:new, :create, :cancel]
  skip_before_filter :require_no_authentication
 
  def check_permissions
    authorize! :create, resource
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  # GET /workouts
  # GET /workouts.json
  
  load_and_authorize_resource
  
  def index
    @workouts = Workout.all
    render :layout => "list"
    
    #respond_to do |format|
      #format.html # index.html.erb
      #format.json { render json: @workouts }
    #end
  end
  
  def random
    @equipment_ids = params[:workout][:equipment_ids].collect{|s| s.to_i} # grabs equipment id's from params and turns back into an array of integers
    @all_equipment_ids = Equipment.all(:select => :id).collect(&:id)      # returns an array of all equipment ids
    @equipment_dont_have = (@all_equipment_ids - @equipment_ids) * ","    # returns an array of all the equipment the user doesn't have
    @workouts = Workout.joins("left join equipment_workouts on workout_id = workouts.id and equipment_id in (#{@equipment_dont_have})").where("equipment_id is null")
    @workout = @workouts.sample
    
    respond_to do |format|
    format.html # random.html.erb
    format.json { render json: @workout }
    end
  end

  # GET /workouts/1
  # GET /workouts/1.json
  def show
    @workout = Workout.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/new
  # GET /workouts/new.json
  def new
    @workout = Workout.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @workout }
    end
  end

  # GET /workouts/1/edit
  def edit
    @workout = Workout.find(params[:id])
  end

  # POST /workouts
  # POST /workouts.json
  def create
    @workout = Workout.new(params[:workout])

    respond_to do |format|
      if @workout.save
        format.html { redirect_to @workout, notice: 'Workout was successfully created.' }
        format.json { render json: @workout, status: :created, location: @workout }
      else
        format.html { render action: "new" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workouts/1
  # PUT /workouts/1.json
  def update
    @workout = Workout.find(params[:id])

    respond_to do |format|
      if @workout.update_attributes(params[:workout])
        format.html { redirect_to @workout, notice: 'Workout was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1
  # DELETE /workouts/1.json
  def destroy
    @workout = Workout.find(params[:id])
    @workout.destroy

    respond_to do |format|
      format.html { redirect_to workouts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/equipment/_form.html.erb
<%= form_for @equipment, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                equipment_path, :class => 'btn' %>
  </div>
<% end %>

app/views/equipment/edit.html.erb
<%- model_class = @equipment.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/equipment/index.html.erb
<%- model_class = Equipment.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @equipment.each do |equipment| %>
      <tr>
        <td><%= link_to equipment.id, equipment_path(equipment) %></td>
        <td><%= equipment.name %></td>
        <td><%=l equipment.created_at %></td>
        <td>
          <% if can? :update, @equipment %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_equipment_path(equipment), :class => 'btn btn-mini' %>
          <% end %>
          <% if can? :destroy, @equipment %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      equipment_path(equipment),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, @equipment %>
  <%= link_to t('.new', :default => t("helpers.links.new")), 
  new_equipment_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/equipment/new.html.erb
<%- model_class = @equipment.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= form_for @equipment, :url=> {:action=>'create'}, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                equipment_index_path, :class => 'btn' %>
  </div>
<% end %>

app/views/equipment/show.html.erb
<%- model_class = @equipment.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @equipment.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              equipment_path, :class => 'btn'  %>
  <% if can? :update, @equipment %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_equipment_path(@equipment), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, @equipment %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              equipment_path(@equipment),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/home/index.html.erb
<%- model_class = @workout.class -%>
<div class="page-header">
  <h1>Get a Random CrossFit Workout</h1>
</div>
<%= form_tag({:controller => "workouts", :action => "random"}) do %>
<p>Choose your available equipment:<br />
  <div class="control-group">
    <div class="controls equipment">
    <%= hidden_field_tag "workout[equipment_ids][]", nil %>
    <% Equipment.all.each do |equipment| #loop through all Equipment objects %>
      <%= check_box_tag "workout[equipment_ids][]", equipment.id, false, id: dom_id(equipment) %>
      <%= label_tag dom_id(equipment), equipment.name %><br>
    <% end %>
    </div>
  </div>
  <div class="form-actions">
    <%= submit_tag "Get Workout", :class => 'btn btn-primary' %>
  </div>
<% end %>
<% if can? :create, @workout %>
<p><%=link_to "Add a minimal equipment workout", new_workout_path %></p>
<% end %>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WorkoutX</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="/home">WorkoutX</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Random", root_path %></li>
            <li><%= link_to "All", workouts_path %></li>
          </ul>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% else %>
            <li><%= link_to "Admin", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<%= render :partial => 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="span3">
        <h2>WorkoutX</h2>
        <p>WorkoutX provides a random CrossFit workout based on the equipment you have available to you. Ideal for working out while on the go, travelling, in your lunch break or any other time you have access to limited equipment.</p>
        <br />
        <h3>What is CrossFit?</h3>
        <p>CrossFit workouts are constantly varied, high intensity workouts that focus on functional movements to improve fitness and general physical preparedness. You can learn more at <%= link_to 'CrossFit.com', 'http://crossfit.com' %>.</p>
      </div>
      <div class="span1">
        &nbsp;
      </div>
      <div class="span8">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">x</a>
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/list.html.erb
<%= render :partial => 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div class="span12">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
            <a class="close" data-dismiss="alert">x</a>
            <%= msg %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for @workout, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area', :rows => 10 %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls equipment">
      <%= hidden_field_tag "workout[equipment_ids][]", nil %>
      <% Equipment.all.each do |equipment| %>
        <%= check_box_tag "workout[equipment_ids][]", equipment.id, @workout.equipment_ids.include?(equipment.id), id: dom_id(equipment) %>
        <%= label_tag dom_id(equipment), equipment.name %><br>
      <% end %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :source, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :source, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                workouts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/workouts/edit.html.erb
<%- model_class = @workout.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workouts/index.html.erb
<%- model_class = Workout.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:equipment) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th>
      <% if can? :update, @workout %>
        <%=t '.actions', :default => t("helpers.actions") %>
      <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @workouts.each do |workout| %>
      <tr>
        <td><%= link_to workout.id, workout_path(workout) %></td>
        <td><%= workout.title %></td>
        <td><%= simple_format(workout.description) %></td>
        <td><% workout.equipment.each do |equipment| %><%= equipment.name %><br /><% end %></td>
        <td><%= workout.source %></td>
        <td>
          <% if can? :update, @workout %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_workout_path(workout), :class => 'btn btn-mini' %>
          <% end %>
          <% if can? :destroy, @workout %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      workout_path(workout),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if can? :create, @workout %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_workout_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/workouts/new.html.erb
<%- model_class = @workout.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/workouts/random.html.erb
<%- model_class = @workout.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @workout.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= simple_format(@workout.description) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:equipment) %>:</strong></dt>
  <dd><ul>
    <% if @workout.equipment == [] %>
      <li>None required</li><% end %>
  <% @workout.equipment.each do |equipment| %>
  <li><%= equipment.name %></li>
  <% end %>
  </ul></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @workout.source %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              workouts_path, :class => 'btn'  %>
  <% if can? :update, @workout %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_workout_path(@workout), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, @workout %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              workout_path(@workout),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
</div>

app/views/workouts/show.html.erb
<%- model_class = @workout.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @workout.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= simple_format(@workout.description) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:equipment) %>:</strong></dt>
  <dd><ul>
    <% if @workout.equipment == [] %>
      <li>None required</li><% end %>
  <% @workout.equipment.each do |equipment| %>
  <li><%= equipment.name %></li>
  <% end %>
  </ul></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @workout.source %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              workouts_path, :class => 'btn'  %>
  <% if can? :update, @workout %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_workout_path(@workout), :class => 'btn' %>
  <% end %>
  <% if can? :destroy, @workout %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              workout_path(@workout),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
  <% end %>
</div>